# Getting and Knowing Data

In [8]:
import pandas as pd
import numpy as np

# Step 1 : Import Dataset

In [9]:
df = pd.read_csv("chipotle.tsv", sep = "\t")

In [10]:
df.head(5)

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98

Note : NaN (Not a number) : null value

# Step Dataset overview

In [11]:
df.shape

(4622, 5)

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            4622 non-null   int64
 1   quantity            4622 non-null   int64
 2   item_name           4622 non-null   object
 3   choice_description  3376 non-null   object
 4   item_price          4622 non-null   object
dtypes: int64(2), object(3)
memory usage: 180.7+ KB

Note: So sánh số giá trị non-null với tổng data (tổng hàng) để xem feature nào bị null để clean

Với các kiểu khác int và float như String , .. đều tính là object

In [13]:
df.columns

Index(['order_id', 'quantity', 'item_name', 'choice_description',
       'item_price'],
      dtype='object')

Note : Liệt kê tất cả các feature(các cột)

In [14]:
df.describe()

          order_id     quantity
count  4622.000000  4622.000000
mean    927.254868     1.075725
std     528.890796     0.410186
min       1.000000     1.000000
25%     477.250000     1.000000
50%     926.000000     1.000000
75%    1393.000000     1.000000
max    1834.000000    15.000000

Note : chỉ có thể liệt kê ra cá feature mà không phải object nên chỉ có 2 feature

In [15]:
df.describe(include ="all")

           order_id     quantity     item_name choice_description item_price
count   4622.000000  4622.000000          4622               3376       4622
unique          NaN          NaN            50               1043         78
top             NaN          NaN  Chicken Bowl        [Diet Coke]     $8.75
freq            NaN          NaN           726                134        730
mean     927.254868     1.075725           NaN                NaN        NaN
std      528.890796     0.410186           NaN                NaN        NaN
min        1.000000     1.000000           NaN                NaN        NaN
25%      477.250000     1.000000           NaN                NaN        NaN
50%      926.000000     1.000000           NaN                NaN        NaN
75%     1393.000000     1.000000           NaN                NaN        NaN
max     1834.000000    15.000000           NaN                NaN        NaN

Note : Include all kể các object

In [16]:
df.loc[df['quantity'] == 15]

,order_id,quantity,item_name,choice_description,item_price
3598,1443,15,Chips and Fresh Tomato Salsa,NaN,$44.25

In [17]:
df.loc[df.quantity == 15]

,order_id,quantity,item_name,choice_description,item_price
3598,1443,15,Chips and Fresh Tomato Salsa,NaN,$44.25

Note : loc như 1 dạng filter, như ở ví dụ trên nó sẽ trả về chỗ mà có quantity bằng 15

Có 2 cách để lấy giá trị feature như 2 cell trên

In [18]:
df.loc[(df.quantity > 12) | (df.item_name == "Chips and Fresh Tomato Salsa")]

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
25,13,1,Chips and Fresh Tomato Salsa,NaN,$2.39
55,25,1,Chips and Fresh Tomato Salsa,NaN,$2.39
89,39,1,Chips and Fresh Tomato Salsa,NaN,$2.95
183,82,1,Chips and Fresh Tomato Salsa,NaN,$2.95
...,...,...,...,...,...
4231,1689,1,Chips and Fresh Tomato Salsa,NaN,$2.95
4318,1722,1,Chips and Fresh Tomato Salsa,NaN,$2.95
4324,1725,1,Chips and Fresh Tomato Salsa,NaN,$2.95
4425,1764,1,Chips and Fresh Tomato Salsa,NaN,$2.95
4503,1790,1,Chips and Fresh Tomato Salsa,NaN,$2.95

Note : or : | chứ không phải là  ||

In [19]:
df.loc[(df.quantity > 12) & (df.item_name == "Chips and Fresh Tomato Salsa")]

,order_id,quantity,item_name,choice_description,item_price
3598,1443,15,Chips and Fresh Tomato Salsa,NaN,$44.25

In [20]:
df.loc[(df.quantity > 12) & (df.item_name == "Chips and Fresh Tomato Salsa"), ['order_id', 'quantity']]

      order_id  quantity
3598      1443        15

Note : biến số thứ 2 là 1 list chứa các features muốn được filter

In [21]:
df.loc[0]

order_id                                         1
quantity                                         1
item_name             Chips and Fresh Tomato Salsa
choice_description                             NaN
item_price                                  $2.39
Name: 0, dtype: object

In [22]:
df.iloc[0]

order_id                                         1
quantity                                         1
item_name             Chips and Fresh Tomato Salsa
choice_description                             NaN
item_price                                  $2.39
Name: 0, dtype: object

Note: tìm kiếm theo index , bắt đầu từ 0 đến n-1

In [23]:
df.iloc[[0]]

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39

NOTE : Hiển thị theo dạng DataFrame, chỉ cần thêm nếu chỉ cần lấy 1 hàng

In [24]:
df.iloc[3 : 10]

,order_id,quantity,item_name,choice_description,item_price
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98
6,3,1,Side of Chips,NaN,$1.69
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.75
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",$9.25
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",$9.25

NOTE : Viết kiểu này sẽ chạy từ a - 1 -> n - 1

In [25]:
df.iloc[3 : 10, 0 : -1]

,order_id,quantity,item_name,choice_description
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans..."
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou..."
6,3,1,Side of Chips,NaN
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables..."
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch..."
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto..."

NOTE : slice cut => a : b  -> lấy từ a đến b - 1

# Data Manipulation

In [26]:
df.item_price.dtype

dtype('O')

NOTE : 
    'b'       boolean
    'i'       (signed) integer
    'u'       unsigned integer
    'f'       floating-point
    'c'       complex-floating point
    'O'       (Python) objects
    'S', 'a'  (byte-)string
    'U'       Unicode
    'V'       raw data (void)

# Apply()

In [29]:
df.item_price.apply(lambda x : x.replace('$', ''))

0        2.39
1        3.39
2        3.39
3        2.39
4       16.98
         ...
4617    11.75
4618    11.75
4619    11.25
4620     8.75
4621     8.75
Name: item_price, Length: 4622, dtype: object

NOTE : Loại bỏ Đô la của label, đưa định dạng về float

df.apply(func, axis=0) 
func: Là hàm mà bạn muốn áp dụng cho mỗi phần tử hoặc cột.
axis: Được sử dụng để xác định liệu bạn muốn áp dụng hàm theo cột (axis=0) hay theo hàng (axis=1).

In [30]:
X = df.item_price.apply(lambda x : x.replace('$', ''))
X.dtype

dtype('O')

In [33]:
X = df.item_price.apply(lambda x : float(x.replace('$', '')))
X.dtype

dtype('float64')

In [34]:
df.item_price = X

Chuyển dữ liệu vừa xử lí thay thế cho dữ liệu cũ trong bảng

In [36]:
df.head()

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39
1,1,1,Izze,[Clementine],3.39
2,1,1,Nantucket Nectar,[Apple],3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98

###Tạo cột mới

In [37]:
#df.total_price = df.item_price * df.quantity

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_8268\4101891353.py:1: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  df.total_price = df.item_price * df.quantity

Nếu tạo cột mới thì cách này là sai vì sẽ dẫn đến lỗi này :  UserWarning: Pandas doesn't allow columns to be created via a new attribute name

In [38]:
df['total_price'] = df['item_price'] * df['quantity']

In [39]:
df.head()

,order_id,quantity,item_name,choice_description,item_price,total_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39,2.39
1,1,1,Izze,[Clementine],3.39,3.39
2,1,1,Nantucket Nectar,[Apple],3.39,3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98,33.96

# How much was the revenue for the period in the datasheet?

In [40]:
sum_price = df.total_price.sum()
print(sum_price)

39237.02

Tổng doanh thu trong dataset

# Sản phẩm nào được mua nhiều nhất ( What was the most odered item ?)

# Group By

In [42]:
df.groupby("item_name")

In [43]:
df.groupby("item_name").apply(print)

      order_id  quantity          item_name choice_description  item_price  \
298        129         1  6 Pack Soft Drink           [Sprite]        6.49
341        148         1  6 Pack Soft Drink        [Diet Coke]        6.49
357        154         1  6 Pack Soft Drink             [Coke]        6.49
388        168         1  6 Pack Soft Drink        [Diet Coke]        6.49
417        182         1  6 Pack Soft Drink        [Diet Coke]        6.49
553        230         1  6 Pack Soft Drink        [Diet Coke]        6.49
639        264         1  6 Pack Soft Drink        [Diet Coke]        6.49
721        298         1  6 Pack Soft Drink           [Nestea]        6.49
743        306         1  6 Pack Soft Drink             [Coke]        6.49
879        363         1  6 Pack Soft Drink             [Coke]        6.49
1026       422         1  6 Pack Soft Drink           [Sprite]        6.49
1051       432         1  6 Pack Soft Drink             [Coke]        6.49
1124       465         1  6 Pack Soft Drink             [Coke]        6.49
1167       481         1  6 Pack Soft Drink             [Coke]        6.49
1260       511         1  6 Pack Soft Drink             [Coke]        6.49
1279       520         1  6 Pack Soft Drink           [Sprite]        6.49
1392       566         1  6 Pack Soft Drink        [Diet Coke]        6.49
1755       708         1  6 Pack Soft Drink             [Coke]        6.49
1758       709         1  6 Pack Soft Drink        [Diet Coke]        6.49
1849       749         1  6 Pack Soft Drink             [Coke]        6.49
1860       754         1  6 Pack Soft Drink        [Diet Coke]        6.49
1916       774         1  6 Pack Soft Drink        [Diet Coke]        6.49
1922       776         1  6 Pack Soft Drink             [Coke]        6.49
1937       784         1  6 Pack Soft Drink        [Diet Coke]        6.49
1976       798         1  6 Pack Soft Drink        [Diet Coke]        6.49
2108       849         1  6 Pack Soft Drink             [Coke]        6.49
2232       899         1  6 Pack Soft Drink             [Coke]        6.49
2374       945         1  6 Pack Soft Drink           [Sprite]        6.49
2389       949         1  6 Pack Soft Drink             [Coke]        6.49
2713      1076         1  6 Pack Soft Drink             [Coke]        6.49
2793      1109         1  6 Pack Soft Drink        [Diet Coke]        6.49
2860      1136         1  6 Pack Soft Drink        [Diet Coke]        6.49
3010      1196         1  6 Pack Soft Drink        [Diet Coke]        6.49
3132      1248         1  6 Pack Soft Drink        [Diet Coke]        6.49
3141      1253         1  6 Pack Soft Drink         [Lemonade]        6.49
3389      1360         2  6 Pack Soft Drink        [Diet Coke]       12.98
3422      1373         1  6 Pack Soft Drink             [Coke]        6.49
3600      1443         1  6 Pack Soft Drink             [Coke]        6.49
3614      1448         1  6 Pack Soft Drink           [Nestea]        6.49
3633      1454         1  6 Pack Soft Drink             [Coke]        6.49
3693      1480         1  6 Pack Soft Drink        [Diet Coke]        6.49
3766      1508         1  6 Pack Soft Drink             [Coke]        6.49
3789      1517         1  6 Pack Soft Drink        [Diet Coke]        6.49
3806      1525         1  6 Pack Soft Drink           [Sprite]        6.49
3836      1537         1  6 Pack Soft Drink             [Coke]        6.49
3875      1554         1  6 Pack Soft Drink        [Diet Coke]        6.49
3886      1558         1  6 Pack Soft Drink        [Diet Coke]        6.49
4169      1664         1  6 Pack Soft Drink        [Diet Coke]        6.49
4174      1666         1  6 Pack Soft Drink             [Coke]        6.49
4359      1741         1  6 Pack Soft Drink             [Coke]        6.49
4363      1742         1  6 Pack Soft Drink        [Diet Coke]        6.49
4522      1798         1  6 Pack Soft Drink        [Diet Coke]        6.49
4527      1800         1  6 Pack Soft Drink        [Diet Coke]        6.49
4535      1803         1  6 Pack Soft Drink         [Lemonade]        6.49

      total_price
298          6.49
341          6.49
357          6.49
388          6.49
417          6.49
553          6.49
639          6.49
721          6.49
743          6.49
879          6.49
1026         6.49
1051         6.49
1124         6.49
1167         6.49
1260         6.49
1279         6.49
1392         6.49
1755         6.49
1758         6.49
1849         6.49
1860         6.49
1916         6.49
1922         6.49
1937         6.49
1976         6.49
2108         6.49
2232         6.49
2374         6.49
2389         6.49
2713         6.49
2793         6.49
2860         6.49
3010         6.49
3132         6.49
3141         6.49
3389        25.96
3422         6.49
3600         6.49
3614         6.49
3633         6.49
3693         6.49
3766         6.49
3789         6.49
3806         6.49
3836         6.49
3875         6.49
3886         6.49
4169         6.49
4174         6.49
4359         6.49
4363         6.49
4522         6.49
4527         6.49
4535         6.49
      order_id  quantity      item_name  \
39          19         1  Barbacoa Bowl
58          27         1  Barbacoa Bowl
95          42         1  Barbacoa Bowl
115         51         1  Barbacoa Bowl
127         56         1  Barbacoa Bowl
...        ...       ...            ...
4380      1748         1  Barbacoa Bowl
4441      1770         1  Barbacoa Bowl
4485      1786         1  Barbacoa Bowl
4510      1793         1  Barbacoa Bowl
4594      1825         1  Barbacoa Bowl

                                     choice_description  item_price  \
39    [Roasted Chili Corn Salsa, [Fajita Vegetables,...       11.75
58    [Roasted Chili Corn Salsa, [Fajita Vegetables,...       11.75
95    [Fresh Tomato Salsa, [Fajita Vegetables, Rice,...        9.25
115   [[Tomatillo-Red Chili Salsa (Hot), Tomatillo-G...        8.99
127   [Tomatillo Red Chili Salsa, [Rice, Pinto Beans...        9.25
...                                                 ...         ...
4380  [Fresh Tomato Salsa, [Fajita Vegetables, Rice,...       11.75
4441  [Tomatillo Green Chili Salsa, [Rice, Cheese, G...       11.75
4485  [Fresh Tomato Salsa, [Fajita Vegetables, Rice,...       11.75
4510                                        [Guacamole]       11.49
4594  [Roasted Chili Corn Salsa, [Pinto Beans, Sour ...       11.75

      total_price
39          11.75
58          11.75
95           9.25
115          8.99
127          9.25
...           ...
4380        11.75
4441        11.75
4485        11.75
4510        11.49
4594        11.75

[66 rows x 6 columns]
      order_id  quantity         item_name  \
21          11         1  Barbacoa Burrito
81          36         1  Barbacoa Burrito
121         53         1  Barbacoa Burrito
130         57         1  Barbacoa Burrito
144         65         1  Barbacoa Burrito
...        ...       ...               ...
4355      1739         1  Barbacoa Burrito
4358      1740         1  Barbacoa Burrito
4592      1825         1  Barbacoa Burrito
4602      1827         1  Barbacoa Burrito
4603      1827         1  Barbacoa Burrito

                                     choice_description  item_price  \
21    [[Fresh Tomato Salsa (Mild), Tomatillo-Green C...        8.99
81    [Fresh Tomato Salsa, [Rice, Pinto Beans, Chees...        9.25
121   [Tomatillo Green Chili Salsa, [Rice, Black Bea...        9.25
130   [Roasted Chili Corn Salsa, [Rice, Pinto Beans,...       11.75
144   [Tomatillo Red Chili Salsa, [Rice, Sour Cream,...       11.75
...                                                 ...         ...
4355  [Roasted Chili Corn Salsa, [Fajita Vegetables,...       11.75
4358  [Fresh Tomato Salsa, [Rice, Black Beans, Chees...        9.25
4592  [Tomatillo Red Chili Salsa, [Rice, Fajita Vege...       11.75
4602                      [Tomatillo Green Chili Salsa]        9.25
4603                      [Tomatillo Green Chili Salsa]        9.25

      total_price
21           8.99
81           9.25
121          9.25
130         11.75
144         11.75
...           ...
4355        11.75
4358         9.25
4592        11.75
4602         9.25
4603         9.25

[91 rows x 6 columns]
      order_id  quantity              item_name  \
168         75         1  Barbacoa Crispy Tacos
255        110         1  Barbacoa Crispy Tacos
429        186         1  Barbacoa Crispy Tacos
485        205         1  Barbacoa Crispy Tacos
763        315         1  Barbacoa Crispy Tacos
829        343         1  Barbacoa Crispy Tacos
1019       419         1  Barbacoa Crispy Tacos
1866       756         1  Barbacoa Crispy Tacos
1903       768         2  Barbacoa Crispy Tacos
2787      1106         1  Barbacoa Crispy Tacos
3321      1330         1  Barbacoa Crispy Tacos

                                     choice_description  item_price  \
168   [Tomatillo Red Chili Salsa, [Rice, Black Beans...       11.75
255   [Roasted Chili Corn Salsa, [Rice, Cheese, Lett...        9.25
429   [[Roasted Chili Corn Salsa (Medium), Tomatillo...       11.48
485                     [Fresh Tomato Salsa, Guacamole]       11.75
763         [Fresh Tomato Salsa, [Sour Cream, Lettuce]]        9.25
829   [Roasted Chili Corn Salsa, [Fajita Vegetables,...        9.25
1019  [Tomatillo-Red Chili Salsa (Hot), [Black Beans...        8.99
1866   [Fresh Tomato Salsa, [Rice, Cheese, Sour Cream]]        9.25
1903   [Fresh Tomato Salsa, [Sour Cream, Cheese, Rice]]       18.50
2787  [Roasted Chili Corn Salsa, [Rice, Cheese, Lett...       11.75
3321  [[Fresh Tomato Salsa (Mild), Tomatillo-Green C...        8.99

      total_price
168         11.75
255          9.25
429         11.48
485         11.75
763          9.25
829          9.25
1019         8.99
1866         9.25
1903        37.00
2787        11.75
3321         8.99
      order_id  quantity            item_name  \
1229       501         1  Barbacoa Salad Bowl
1326       541         1  Barbacoa Salad Bowl
1418       576         1  Barbacoa Salad Bowl
1421       576         1  Barbacoa Salad Bowl
1825       738         1  Barbacoa Salad Bowl
2442       970         1  Barbacoa Salad Bowl
3208      1283         1  Barbacoa Salad Bowl
3356      1346         1  Barbacoa Salad Bowl
3546      1426         1  Barbacoa Salad Bowl
4390      1751         1  Barbacoa Salad Bowl

                                     choice_description  item_price  \
1229  [Fresh Tomato Salsa, [Rice, Fajita Vegetables,...       11.89
1326  [Fresh Tomato Salsa, [Fajita Vegetables, Rice,...       11.89
1418                         [Roasted Chili Corn Salsa]        9.39
1421                         [Roasted Chili Corn Salsa]        9.39
1825  [Fresh Tomato Salsa, [Rice, Pinto Beans, Chees...        9.39
2442  [Tomatillo Green Chili Salsa, [Rice, Fajita Ve...       11.89
3208  [Tomatillo Red Chili Salsa, [Black Beans, Chee...       11.89
3356  [Fresh Tomato Salsa, [Rice, Black Beans, Chees...        9.39
3546                    [Fresh Tomato Salsa, Guacamole]       11.89
4390  [Tomatillo Green Chili Salsa, [Fajita Vegetabl...        9.39

      total_price
1229        11.89
1326        11.89
1418         9.39
1421         9.39
1825         9.39
2442        11.89
3208        11.89
3356         9.39
3546        11.89
4390         9.39
      order_id  quantity            item_name  \
56          26         1  Barbacoa Soft Tacos
181         82         1  Barbacoa Soft Tacos
268        117         1  Barbacoa Soft Tacos
611        252         1  Barbacoa Soft Tacos
857        353         1  Barbacoa Soft Tacos
988        406         1  Barbacoa Soft Tacos
1129       467         1  Barbacoa Soft Tacos
1149       475         1  Barbacoa Soft Tacos
1240       506         1  Barbacoa Soft Tacos
1334       545         1  Barbacoa Soft Tacos
1391       565         1  Barbacoa Soft Tacos
1642       663         1  Barbacoa Soft Tacos
1669       675         1  Barbacoa Soft Tacos
1754       708         1  Barbacoa Soft Tacos
1985       803         1  Barbacoa Soft Tacos
2083       841         1  Barbacoa Soft Tacos
2248       906         1  Barbacoa Soft Tacos
2259       910         1  Barbacoa Soft Tacos
2434       966         1  Barbacoa Soft Tacos
2780      1103         1  Barbacoa Soft Tacos
3184      1273         1  Barbacoa Soft Tacos
3211      1284         1  Barbacoa Soft Tacos
3548      1426         1  Barbacoa Soft Tacos
4182      1670         1  Barbacoa Soft Tacos
4271      1703         1  Barbacoa Soft Tacos

                                     choice_description  item_price  \
56    [Fresh Tomato Salsa, [Fajita Vegetables, Black...        9.25
181   [Tomatillo Red Chili Salsa, [Rice, Pinto Beans...        9.25
268   [Tomatillo-Red Chili Salsa (Hot), [Pinto Beans...        8.99
611   [Tomatillo Red Chili Salsa, [Rice, Pinto Beans...        9.25
857   [Tomatillo Red Chili Salsa, [Rice, Pinto Beans...        9.25
988   [Tomatillo Red Chili Salsa, [Black Beans, Chee...       11.75
1129  [Roasted Chili Corn Salsa, [Rice, Pinto Beans,...       11.75
1149  [Tomatillo Green Chili Salsa, [Sour Cream, Che...        9.25
1240  [Tomatillo Red Chili Salsa, [Rice, Pinto Beans...        9.25
1334  [Roasted Chili Corn Salsa, [Rice, Cheese, Sour...       11.75
1391  [Tomatillo Red Chili Salsa, [Rice, Cheese, Sou...        9.25
1642  [[Fresh Tomato Salsa (Mild), Roasted Chili Cor...        8.99
1669  [Tomatillo Red Chili Salsa, [Rice, Cheese, Sou...        9.25
1754  [Tomatillo Green Chili Salsa, [Pinto Beans, So...       11.75
1985  [Fresh Tomato Salsa, [Black Beans, Cheese, Let...        9.25
2083  [Fresh Tomato Salsa, [Rice, Black Beans, Pinto...        9.25
2248  [Tomatillo Red Chili Salsa, [Rice, Cheese, Sou...        9.25
2259  [Tomatillo Red Chili Salsa, [Rice, Pinto Beans...        9.25
2434  [Roasted Chili Corn Salsa, [Cheese, Sour Cream...       11.75
2780  [Tomatillo Red Chili Salsa, [Rice, Pinto Beans...        9.25
3184  [Tomatillo-Red Chili Salsa (Hot), [Rice, Chees...       11.48
3211  [Roasted Chili Corn Salsa, [Rice, Black Beans,...       11.75
3548  [Tomatillo Red Chili Salsa, [Fajita Vegetables...       11.75
4182  [Tomatillo Red Chili Salsa, [Rice, Cheese, Sou...        9.25
4271  [Roasted Chili Corn Salsa, [Fajita Vegetables,...        9.25

      total_price
56           9.25
181          9.25
268          8.99
611          9.25
857          9.25
988         11.75
1129        11.75
1149         9.25
1240         9.25
1334        11.75
1391         9.25
1642         8.99
1669         9.25
1754        11.75
1985         9.25
2083         9.25
2248         9.25
2259         9.25
2434        11.75
2780         9.25
3184        11.48
3211        11.75
3548        11.75
4182         9.25
4271         9.25
      order_id  quantity      item_name choice_description  item_price  \
34          17         1  Bottled Water                NaN        1.09
87          38         1  Bottled Water                NaN        1.09
318        138         1  Bottled Water                NaN        1.09
329        143         1  Bottled Water                NaN        1.50
376        163         1  Bottled Water                NaN        1.50
...        ...       ...            ...                ...         ...
4568      1817         1  Bottled Water                NaN        1.50
4570      1817         1  Bottled Water                NaN        1.50
4582      1822         2  Bottled Water                NaN        3.00
4598      1826         1  Bottled Water                NaN        1.50
4614      1831         1  Bottled Water                NaN        1.50

      total_price
34           1.09
87           1.09
318          1.09
329          1.50
376          1.50
...           ...
4568         1.50
4570         1.50
4582         6.00
4598         1.50
4614         1.50

[162 rows x 6 columns]
     order_id  quantity item_name  \
445       193         3      Bowl
673       279         1      Bowl

                                    choice_description  item_price  \
445  [Braised Carnitas, Pinto Beans, [Sour Cream, C...        22.2
673  [Adobo-Marinated and Grilled Steak, [Sour Crea...         7.4

     total_price
445         66.6
673          7.4
     order_id  quantity item_name  \
510       214         1   Burrito
511       214         1   Burrito
519       217         1   Burrito
675       279         1   Burrito
759       313         1   Burrito
760       313         1   Burrito

                                    choice_description  item_price  \
510  [Adobo-Marinated and Grilled Chicken, Pinto Be...         7.4
511  [Braised Barbacoa, Vegetarian Black Beans, [So...         7.4
519  [Braised Barbacoa, Pinto Beans, [Sour Cream, S...         7.4
675  [Adobo-Marinated and Grilled Chicken, [Sour Cr...         7.4
759  [White Rice, Adobo-Marinated and Grilled Steak...         7.4
760  [White Rice, Adobo-Marinated and Grilled Steak...         7.4

     total_price
510          7.4
511          7.4
519          7.4
675          7.4
759          7.4
760          7.4
      order_id  quantity    item_name choice_description  item_price  \
18           9         2  Canned Soda           [Sprite]        2.18
28          14         1  Canned Soda       [Dr. Pepper]        1.09
51          23         2  Canned Soda     [Mountain Dew]        2.18
53          24         1  Canned Soda           [Sprite]        1.09
107         47         1  Canned Soda       [Dr. Pepper]        1.09
...        ...       ...          ...                ...         ...
3897      1562         1  Canned Soda     [Mountain Dew]        1.09
3926      1575         1  Canned Soda       [Dr. Pepper]        1.09
3936      1578         1  Canned Soda  [Diet Dr. Pepper]        1.09
4008      1604         1  Canned Soda        [Diet Coke]        1.09
4051      1621         1  Canned Soda           [Sprite]        1.09

      total_price
18           4.36
28           1.09
51           4.36
53           1.09
107          1.09
...           ...
3897         1.09
3926         1.09
3936         1.09
4008         1.09
4051         1.09

[104 rows x 6 columns]
      order_id  quantity          item_name choice_description  item_price  \
263        114         1  Canned Soft Drink             [Coke]        1.25
292        127         1  Canned Soft Drink           [Sprite]        1.25
320        139         1  Canned Soft Drink             [Coke]        1.25
337        147         1  Canned Soft Drink             [Coke]        1.25
346        149         1  Canned Soft Drink         [Lemonade]        1.25
...        ...       ...                ...                ...         ...
4585      1823         1  Canned Soft Drink        [Diet Coke]        1.25
4597      1826         1  Canned Soft Drink           [Nestea]        1.25
4601      1827         1  Canned Soft Drink        [Diet Coke]        1.25
4606      1828         1  Canned Soft Drink             [Coke]        1.25
4609      1829         1  Canned Soft Drink           [Sprite]        1.25

      total_price
263          1.25
292          1.25
320          1.25
337          1.25
346          1.25
...           ...
4585         1.25
4597         1.25
4601         1.25
4606         1.25
4609         1.25

[301 rows x 6 columns]
      order_id  quantity      item_name  \
33          17         1  Carnitas Bowl
97          43         1  Carnitas Bowl
145         65         1  Carnitas Bowl
163         74         1  Carnitas Bowl
399        173         1  Carnitas Bowl
...        ...       ...            ...
4500      1789         1  Carnitas Bowl
4504      1791         1  Carnitas Bowl
4562      1814         1  Carnitas Bowl
4593      1825         1  Carnitas Bowl
4612      1831         1  Carnitas Bowl

                                     choice_description  item_price  \
33    [Tomatillo-Red Chili Salsa (Hot), [Black Beans...        8.99
97    [Fresh Tomato Salsa, [Fajita Vegetables, Rice,...       11.75

Empty DataFrame
Columns: []
Index: []

nhóm những sản phẩm có tên chung giống nhau lại

In [44]:
df.groupby("item_name")['quantity'].apply(print)

298     1
341     1
357     1
388     1
417     1
553     1
639     1
721     1
743     1
879     1
1026    1
1051    1
1124    1
1167    1
1260    1
1279    1
1392    1
1755    1
1758    1
1849    1
1860    1
1916    1
1922    1
1937    1
1976    1
2108    1
2232    1
2374    1
2389    1
2713    1
2793    1
2860    1
3010    1
3132    1
3141    1
3389    2
3422    1
3600    1
3614    1
3633    1
3693    1
3766    1
3789    1
3806    1
3836    1
3875    1
3886    1
4169    1
4174    1
4359    1
4363    1
4522    1
4527    1
4535    1
Name: 6 Pack Soft Drink, dtype: int64
39      1
58      1
95      1
115     1
127     1
       ..
4380    1
4441    1
4485    1
4510    1
4594    1
Name: Barbacoa Bowl, Length: 66, dtype: int64
21      1
81      1
121     1
130     1
144     1
       ..
4355    1
4358    1
4592    1
4602    1
4603    1
Name: Barbacoa Burrito, Length: 91, dtype: int64
168     1
255     1
429     1
485     1
763     1
829     1
1019    1
1866    1
1903    2
2787    1
3321    1
Name: Barbacoa Crispy Tacos, dtype: int64
1229    1
1326    1
1418    1
1421    1
1825    1
2442    1
3208    1
3356    1
3546    1
4390    1
Name: Barbacoa Salad Bowl, dtype: int64
56      1
181     1
268     1
611     1
857     1
988     1
1129    1
1149    1
1240    1
1334    1
1391    1
1642    1
1669    1
1754    1
1985    1
2083    1
2248    1
2259    1
2434    1
2780    1
3184    1
3211    1
3548    1
4182    1
4271    1
Name: Barbacoa Soft Tacos, dtype: int64
34      1
87      1
318     1
329     1
376     1
       ..
4568    1
4570    1
4582    2
4598    1
4614    1
Name: Bottled Water, Length: 162, dtype: int64
445    3
673    1
Name: Bowl, dtype: int64
510    1
511    1
519    1
675    1
759    1
760    1
Name: Burrito, dtype: int64
18      2
28      1
51      2
53      1
107     1
       ..
3897    1
3926    1
3936    1
4008    1
4051    1
Name: Canned Soda, Length: 104, dtype: int64
263     1
292     1
320     1
337     1
346     1
       ..
4585    1
4597    1
4601    1
4606    1
4609    1
Name: Canned Soft Drink, Length: 301, dtype: int64
33      1
97      1
145     1
163     1
399     1
       ..
4500    1
4504    1
4562    1
4593    1
4612    1
Name: Carnitas Bowl, Length: 68, dtype: int64
27      1
88      1
93      1
239     1
373     1
421     1
462     1
478     1
626     1
652     1
691     1
767     1
835     1
865     1
959     1
974     1
1063    1
1097    1
1127    1
1197    1
1238    1
1287    1
1337    1
1462    1
1627    1
1677    1
1909    1
1947    1
2032    1
2092    1
2239    1
2270    1
2382    1
2454    1
2523    1
2581    2
2586    1
2686    1
2697    1
2790    1
2884    1
2951    1
3252    1
3421    1
3441    1
3529    1
3619    1
3757    1
3803    1
3882    1
4041    1
4141    1
4249    1
4386    1
4421    1
4437    1
4482    1
4487    1
4578    1
Name: Carnitas Burrito, dtype: int64
554     1
1008    1
1195    1
1632    1
1838    1
3890    2
4450    1
Name: Carnitas Crispy Tacos, dtype: int64
3750    1
Name: Carnitas Salad, dtype: int64
1132    1
1865    1
2610    1
3115    1
3749    1
4239    1
Name: Carnitas Salad Bowl, dtype: int64
237     1
405     1
453     1
565     1
590     1
667     1
755     1
820     1
1186    1
1390    1
1437    1
1587    1
1668    1
1772    1
1789    1
1963    1
2000    1
2080    1
2119    1
2201    1
2247    1
2298    1
2299    1
2551    1
2715    1
2898    1
3067    1
3308    1
3340    1
3341    1
3620    1
3688    1
3695    1
3814    1
3940    1
4095    1
4136    1
4147    1
4326    1
4557    1
Name: Carnitas Soft Tacos, dtype: int64
4       2
5       1
13      1
19      1
26      1
       ..
4590    1
4591    1
4595    1
4599    1
4604    1
Name: Chicken Bowl, Length: 726, dtype: int64
16      1
17      1
23      1
29      1
45      1
       ..
4556    1
4558    1
4559    1
4566    1
4569    1
Name: Chicken Burrito, Length: 553, dtype: int64
11      1
217     2
365     1
598     1
600     1
768     1
830     1
866     1
885     2
946     1
1006    1
1027    1
1345    1
1844    1
2375    1
2422    1
2507    1
2515    1
2549    1
2556    1
2604    1
2651    1
2668    1
2908    1
2912    1
2965    1
3041    1
3072    1
3077    1
3078    1
3099    1
3192    1
3240    1
3309    1
3324    1
3372    1
3472    1
3593    1
3631    1
3638    1
3816    1
3891    2
4116    1
4322    1
4346    1
4371    1
4453    1
Name: Chicken Crispy Tacos, dtype: int64
250     1
1065    1
2968    1
3045    1
3363    1
3730    1
3733    1
3982    1
3989    1
Name: Chicken Salad, dtype: int64
44      1
135     2
213     2
256     1
315     2
       ..
4561    2
4580    1
4619    1
4620    1
4621    1
Name: Chicken Salad Bowl, Length: 110, dtype: int64
12      1
35      1
36      1
75      1
79      1
       ..
4474    1
4502    1
4514    1
4550    1
4615    1
Name: Chicken Soft Tacos, Length: 115, dtype: int64
40      1
59      1
77      1
80      1
208     1
       ..
4505    1
4509    1
4525    1
4584    1
4613    1
Name: Chips, Length: 211, dtype: int64
0       1
25      1
55      1
89      1
183     1
       ..
4231    1
4318    1
4324    1
4425    1
4503    1
Name: Chips and Fresh Tomato Salsa, Length: 110, dtype: int64
10      1
14      1
20      1
37      1
41      1
       ..
4588    1
4596    1
4600    1
4605    1
4616    1
Name: Chips and Guacamole, Length: 479, dtype: int64
674    1
Name: Chips and Mild Fresh Tomato Salsa, dtype: int64
233     1
562     1
708     1
841     1
906     1
1067    1
1150    1
1292    1
1358    1
1371    1
1450    1
1555    2
1597    1
1658    1
1925    1
1962    1
2346    1
2373    1
2602    1
2967    1
3449    1
3780    1
Name: Chips and Roasted Chili Corn Salsa, dtype: int64
191     1
648     1
1180    1
1458    1
1628    1
2053    1
2140    1
2301    1
2371    1
2907    1
3024    1
3054    1
3194    1
3206    1
3268    1
3398    1
3628    1
3905    1
Name: Chips and Roasted Chili-Corn Salsa, dtype: int64
38      1
232     1
235     2
366     1
537     1
627     1
655     1
703     1
782     1
809     1
916     1
1157    1
1259    2
1518    1
1568    1
1573    1
1577    1
1583    1
1589    1
1593    1
1847    1
2296    1
2641    1
2655    1
3257    1
3402    1
3479    1
3513    1
3522    1
3560    1
3562    1
3624    1
3817    1
3901    1
3975    1
3992    1
3995    1
4129    1
4254    1
4328    1
4400    1
4476    1
4493    1
Name: Chips and Tomatillo Green Chili Salsa, dtype: int64
111     1
128     1
356     1
443     1
593     1
838     1
1191    1
1313    1
1348    1
1382    1
1491    1
1620    2
1665    1
1671    1
1732    1
1736    1
1896    1
1915    1
1932    1
1992    1
1999    1
2004    1
2058    1
2103    1
2229    1
2281    1
2330    1
2426    1
2575    1
2576    1
2622    1
2665    1
2743    1
2877    1
3136    1
3292    1
3429    1
3430    1
3482    1
3729    1
4040    1
4131    1
4156    1
4312    2
4320    1
4409    1
4412    1
4466    1
Name: Chips and Tomatillo Red Chili Salsa, dtype: int64
3       1
15      1
30      1
113     1
133     1
153     1
165     1
198     1
271     1
578     1
982     1
1010    1
1018    1
1084    1
1218    1
1263    1
1615    1
1935    1
1967    1
2161    1
2656    2
2848    1
3143    1
3320    1
3573    1
3626    1
3657    2
3788    1
3810    1
3871    1
4007    1
Name: Chips and Tomatillo-Green Chili Salsa, dtype: int64
300     1
349     1
692     1
1101    1
1181    1
1533    1
1534    1
1763    1
1857    1
2011    1
2550    2
2972    3
3052    1
3171    1
3270    3
3358    1
3558    1
3650    1
3660    1
4088    1
Name: Chips and Tomatillo-Red Chili Salsa, dtype: int64
520    1
521    1
Name: Crispy Tacos, dtype: int64
1       1
24      1
47      1
66      1
359     1
360     1
430     1
579     1
580     1
1059    1
1213    1
1611    1
1612    1
1680    1
2088    1
2619    1
2634    1
2758    1
2891    1
3669    1
Name: Izze, dtype: int64
2       1
22      1
105     1
173     1
205     1
436     1
601     2
925     1
1356    1
1585    1
1626    1
1706    1
2162    1
2379    2
2381    1
2430    1
2653    1
2818    1
2838    1
2853    1
2949    1
3318    1
3368    1
3570    1
3845    1
4019    1
4078    1
Name: Nantucket Nectar, dtype: int64
1414    1
1415    1
Name: Salad, dtype: int64
6       1
32      1
70      1
149     1
275     1
       ..
3911    1
3934    1
4055    1
4057    1
4070    1
Name: Side of Chips, Length: 101, dtype: int64
54      1
86      1
90      1
91      1
102     1
       ..
4427    2
4449    1
4459    1
4470    1
4518    1
Name: Steak Bowl, Length: 211, dtype: int64
7       1
9       1
31      1
43      1
46      1
       ..
4546    1
4607    1
4610    1
4617    1
4618    1
Name: Steak Burrito, Length: 368, dtype: int64
92      1
437     1
581     1
729     1
774     1
918     1
1020    1
1168    1
1327    1
1451    1
2025    1
2227    1
2231    1
2418    1
2461    1
2629    1
2812    1
2842    1
2862    1
2874    2
2963    1
3075    1
3085    1
3406    1
3439    1
3503    1
3606    1
3694    1
3778    1
3946    1
3950    1
3994    1
4014    1
4523    1
4554    1
Name: Steak Crispy Tacos, dtype: int64
664     1
752     1
893     1
3502    1
Name: Steak Salad, dtype: int64
281     2
606     1
607     1
613     2
749     1
1159    1
1311    1
1505    1
1571    1
1590    1
1816    1
2401    1
2439    1
2600    1
2624    1
2740    1
2804    1
2957    1
3098    1
3120    1
3350    1
3493    1
4036    1
4241    1
4313    1
4391    1
4419    1
4547    1
4572    1
Name: Steak Salad Bowl, dtype: int64
8       1
61      1
65      1
84      1
118     1
175     1
184     1
266     1
278     1
293     1
299     1
342     1
390     1
494     1
570     1
961     1
968     1
1353    1
1365    1
1542    1
1617    1
1721    1
1912    1
1979    1
2139    1
2144    1
2250    1
2450    1
2654    1
2732    1
2840    1
2844    1
2879    1
3105    1
3205    1
3452    1
3473    1
3569    1
3597    1
3625    1
3705    1
3710    1
3796    1
3870    1
3900    1
3910    1
4038    1
4052    1
4130    1
4181    1
4230    1
4287    1
4297    1
4354    2
4549    1
Name: Steak Soft Tacos, dtype: int64
62      1
85      1
143     1
157     1
164     1
       ..
4282    1
4315    1
4336    1
4452    1
4468    1
Name: Veggie Bowl, Length: 85, dtype: int64
57      1
104     1
225     1
394     1
435     1
       ..
4319    1
4471    1
4519    1
4608    1
4611    1
Name: Veggie Burrito, Length: 95, dtype: int64
1653    1
Name: Veggie Crispy Tacos, dtype: int64
1694    1
2756    1
2996    1
3163    1
3471    1
4084    1
Name: Veggie Salad, dtype: int64
186     1
295     1
455     1
496     1
960     1
1316    1
1884    1
2156    1
2223    1
2269    1
2683    1
3223    1
3293    1
4109    1
4201    1
4261    1
4541    1
4573    1
Name: Veggie Salad Bowl, dtype: int64
738     1
781     1
1395    1
1699    1
2384    1
2851    1
3889    2
Name: Veggie Soft Tacos, dtype: int64

item_name
6 Pack Soft Drink                        None
Barbacoa Bowl                            None
Barbacoa Burrito                         None
Barbacoa Crispy Tacos                    None
Barbacoa Salad Bowl                      None
Barbacoa Soft Tacos                      None
Bottled Water                            None
Bowl                                     None
Burrito                                  None
Canned Soda                              None
Canned Soft Drink                        None
Carnitas Bowl                            None
Carnitas Burrito                         None
Carnitas Crispy Tacos                    None
Carnitas Salad                           None
Carnitas Salad Bowl                      None
Carnitas Soft Tacos                      None
Chicken Bowl                             None
Chicken Burrito                          None
Chicken Crispy Tacos                     None
Chicken Salad                            None
Chicken Salad Bowl                       None
Chicken Soft Tacos                       None
Chips                                    None
Chips and Fresh Tomato Salsa             None
Chips and Guacamole                      None
Chips and Mild Fresh Tomato Salsa        None
Chips and Roasted Chili Corn Salsa       None
Chips and Roasted Chili-Corn Salsa       None
Chips and Tomatillo Green Chili Salsa    None
Chips and Tomatillo Red Chili Salsa      None
Chips and Tomatillo-Green Chili Salsa    None
Chips and Tomatillo-Red Chili Salsa      None
Crispy Tacos                             None
Izze                                     None
Nantucket Nectar                         None
Salad                                    None
Side of Chips                            None
Steak Bowl                               None
Steak Burrito                            None
Steak Crispy Tacos                       None
Steak Salad                              None
Steak Salad Bowl                         None
Steak Soft Tacos                         None
Veggie Bowl                              None
Veggie Burrito                           None
Veggie Crispy Tacos                      None
Veggie Salad                             None
Veggie Salad Bowl                        None
Veggie Soft Tacos                        None
Name: quantity, dtype: object

chỉ in ra quantity

In [47]:
df.groupby("item_name")['quantity'].sum()

item_name
6 Pack Soft Drink                         55
Barbacoa Bowl                             66
Barbacoa Burrito                          91
Barbacoa Crispy Tacos                     12
Barbacoa Salad Bowl                       10
Barbacoa Soft Tacos                       25
Bottled Water                            211
Bowl                                       4
Burrito                                    6
Canned Soda                              126
Canned Soft Drink                        351
Carnitas Bowl                             71
Carnitas Burrito                          60
Carnitas Crispy Tacos                      8
Carnitas Salad                             1
Carnitas Salad Bowl                        6
Carnitas Soft Tacos                       40
Chicken Bowl                             761
Chicken Burrito                          591
Chicken Crispy Tacos                      50
Chicken Salad                              9
Chicken Salad Bowl                       123
Chicken Soft Tacos                       120
Chips                                    230
Chips and Fresh Tomato Salsa             130
Chips and Guacamole                      506
Chips and Mild Fresh Tomato Salsa          1
Chips and Roasted Chili Corn Salsa        23
Chips and Roasted Chili-Corn Salsa        18
Chips and Tomatillo Green Chili Salsa     45
Chips and Tomatillo Red Chili Salsa       50
Chips and Tomatillo-Green Chili Salsa     33
Chips and Tomatillo-Red Chili Salsa       25
Crispy Tacos                               2
Izze                                      20
Nantucket Nectar                          29
Salad                                      2
Side of Chips                            110
Steak Bowl                               221
Steak Burrito                            386
Steak Crispy Tacos                        36
Steak Salad                                4
Steak Salad Bowl                          31
Steak Soft Tacos                          56
Veggie Bowl                               87
Veggie Burrito                            97
Veggie Crispy Tacos                        1
Veggie Salad                               6
Veggie Salad Bowl                         18
Veggie Soft Tacos                          8
Name: quantity, dtype: int64

In [49]:
df.groupby("item_name")['quantity'].sum().sort_values(ascending = False)

item_name
Chicken Bowl                             761
Chicken Burrito                          591
Chips and Guacamole                      506
Steak Burrito                            386
Canned Soft Drink                        351
Chips                                    230
Steak Bowl                               221
Bottled Water                            211
Chips and Fresh Tomato Salsa             130
Canned Soda                              126
Chicken Salad Bowl                       123
Chicken Soft Tacos                       120
Side of Chips                            110
Veggie Burrito                            97
Barbacoa Burrito                          91
Veggie Bowl                               87
Carnitas Bowl                             71
Barbacoa Bowl                             66
Carnitas Burrito                          60
Steak Soft Tacos                          56
6 Pack Soft Drink                         55
Chips and Tomatillo Red Chili Salsa       50
Chicken Crispy Tacos                      50
Chips and Tomatillo Green Chili Salsa     45
Carnitas Soft Tacos                       40
Steak Crispy Tacos                        36
Chips and Tomatillo-Green Chili Salsa     33
Steak Salad Bowl                          31
Nantucket Nectar                          29
Chips and Tomatillo-Red Chili Salsa       25
Barbacoa Soft Tacos                       25
Chips and Roasted Chili Corn Salsa        23
Izze                                      20
Veggie Salad Bowl                         18
Chips and Roasted Chili-Corn Salsa        18
Barbacoa Crispy Tacos                     12
Barbacoa Salad Bowl                       10
Chicken Salad                              9
Carnitas Crispy Tacos                      8
Veggie Soft Tacos                          8
Burrito                                    6
Veggie Salad                               6
Carnitas Salad Bowl                        6
Bowl                                       4
Steak Salad                                4
Salad                                      2
Crispy Tacos                               2
Chips and Mild Fresh Tomato Salsa          1
Carnitas Salad                             1
Veggie Crispy Tacos                        1
Name: quantity, dtype: int64

In [55]:
print(df.groupby("item_name")['quantity'].sum().idxmax(), df.groupby("item_name")['quantity'].sum().max())

Chicken Bowl 761

# Uniqe value

Số data khác nhau trong feature

In [56]:
df.item_name.value_counts()

item_name
Chicken Bowl                             726
Chicken Burrito                          553
Chips and Guacamole                      479
Steak Burrito                            368
Canned Soft Drink                        301
Steak Bowl                               211
Chips                                    211
Bottled Water                            162
Chicken Soft Tacos                       115
Chips and Fresh Tomato Salsa             110
Chicken Salad Bowl                       110
Canned Soda                              104
Side of Chips                            101
Veggie Burrito                            95
Barbacoa Burrito                          91
Veggie Bowl                               85
Carnitas Bowl                             68
Barbacoa Bowl                             66
Carnitas Burrito                          59
Steak Soft Tacos                          55
6 Pack Soft Drink                         54
Chips and Tomatillo Red Chili Salsa       48
Chicken Crispy Tacos                      47
Chips and Tomatillo Green Chili Salsa     43
Carnitas Soft Tacos                       40
Steak Crispy Tacos                        35
Chips and Tomatillo-Green Chili Salsa     31
Steak Salad Bowl                          29
Nantucket Nectar                          27
Barbacoa Soft Tacos                       25
Chips and Roasted Chili Corn Salsa        22
Izze                                      20
Chips and Tomatillo-Red Chili Salsa       20
Veggie Salad Bowl                         18
Chips and Roasted Chili-Corn Salsa        18
Barbacoa Crispy Tacos                     11
Barbacoa Salad Bowl                       10
Chicken Salad                              9
Veggie Soft Tacos                          7
Carnitas Crispy Tacos                      7
Veggie Salad                               6
Carnitas Salad Bowl                        6
Burrito                                    6
Steak Salad                                4
Crispy Tacos                               2
Salad                                      2
Bowl                                       2
Chips and Mild Fresh Tomato Salsa          1
Veggie Crispy Tacos                        1
Carnitas Salad                             1
Name: count, dtype: int64

Số món hàng khác nhau được bán ra và số lượng bán

In [58]:
df.item_name.value_counts().count()

50

Tổng số món khác nhau được bán ra

In [59]:
df.item_name.nunique()

50